import Head from "next/head";
import {Header} from "@/src/components/header";
import {EmployeeNavbar} from "@/src/components/employee/navbar";
import {Footer} from "@/src/components/shared/footer";

export default function EmployeeOrderDetails() {
    return (<>
        <Head>
            <title>Customer Login</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className="main-content">
            <Header/>
            <EmployeeNavbar/>

            <Footer/>
        </div>
    </>)
}
