import Head from "next/head";
import {Header} from "@/src/components/header";
import {Footer} from "@/src/components/shared/footer";
import {Login} from "@/src/components/auth/login";
import Script from "next/script";

export default function LoginForm() {
    return (<>
        <Head>
            <title>RestaurantBuddy - Login</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className="main-content">
            <Header/>
            <div className="title-bar rounded-corners inner-color">
                <h1>RestaurantBuddy - Login</h1>
            </div>
            <Login action="https://localhost:8888/auth/authenticate" method="POST"/>
            <Footer/>
        </div>
        <Script type="text/javascript" src="/js/jquery-3.6.4.min.js"/>
        <Script type="text/javascript" src="/js/auth/login.js"/>
    </>)
}
