version: "0.0.1-dev"

services:
  api:
    build: ./api
    restart: always
    ports:
      - "8888:8888"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
  database:
    image: "mariadb:latest"
    restart: always
    environment:
      MARIADB_USER: restaurantbuddy
      MARIADB_PASSWORD: restaurantbuddy
      MARIADB_DATABASE: restaurantbuddy
      MARIADB_ROOT_PASSWORD: restaurantbuddy
  object:
    image: "minio/minio"
    restart: always
    environment:
      MINIO_ROOT_USER: restaurantbuddy
      MINIO_ROOT_PASSWORD: restaurantbuddy
  phpmyadmin:
    image: "phpmyadmin:latest"
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
