package net.samuelcmace.restaurantbuddyapi;

/**
 * Abstract class encapsulating fields specific to the running instance of the project.
 */
public abstract class DeploymentVariables {

    /**
     * A key, unique to all instances of the project, used to create and manage JWT tokens.
     * This token should be regenerated by any other users who would like to use the project in their own environment.
     */
    public static final String JWT_SECRET_KEY = "4B6250655368566D5970337336763979244226452948404D635166546A576E5A";

}
