custom:
  jwtSecretKey: 4B6250655368566D5970337336763979244226452948404D635166546A576E5A
  minio:
    url: http://localhost:9000/
    username: restaurantbuddy
    password: restaurantbuddy
server:
  port: 8888
spring:
  jpa:
    showSql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddlAuto: update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: restaurantbuddy
    url: jdbc:mariadb://localhost:3306/restaurantbuddy