server:
  address: 0.0.0.0
  port: 8888
  servlet:
    context-path: /api/v1
spring:
  jpa:
    showSql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddlAuto: update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: restaurantbuddy
    url: jdbc:mariadb://database:3306/restaurantbuddy
