server:
  port: 8888
spring:
  jpa:
    showSql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddlAuto:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: restaurantbuddy
    url: jdbc:mariadb://localhost:3306/restaurantbuddy
