import Head from "next/head";
import {Header} from "@/src/components/header";
import {Footer} from "@/src/components/shared/footer";
import {OwnerNavbar} from "@/src/components/owner/navbar";

export default function EmployeeHome() {
    return (<>
        <Head>
            <title>Employee Home</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className="main-content">
            <Header/>
            <OwnerNavbar/>

            <Footer/>
        </div>
    </>)
}
